quant_stage:
  index: 0
  quant_modifiers:
    AWQModifier:
      ignore: ["lm_head"]
      config_groups:
        group_0:
          targets: ["Linear"]
          weights:
            num_bits: 4
            type: "int"
            symmetric: false
            strategy: "group"
            group_size: 128